<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Experience;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // User::factory(10)->create();

        User::factory()->create([
            'name' => 'Test User',
            'email' => 'test@example.com',
        ]);

        $experiences = [
            [
                'title' => 'Recorrido por el Centro Histórico de Oaxaca',
                'desc' => 'Explora la arquitectura colonial, mercados tradicionales y prueba el mezcal local.',
                'available_date' => '2025-06-01',
                'expiration_date' => '2025-09-30',
                'price' => 1200,
                'rating' => 4.7,
                'status' => true,
                'place' => 'Oaxaca, Oaxaca',
                'image' => 'https://images.unsplash.com/photo-1574975201078-bb21d6c7a66d',
            ],
            [
                'title' => 'Salto en paracaídas en Chiapas',
                'desc' => 'Vive la adrenalina con un salto tándem en paisajes selváticos.',
                'available_date' => '2025-06-15',
                'expiration_date' => '2025-12-15',
                'price' => 3500,
                'rating' => 4.9,
                'status' => true,
                'place' => 'Tuxtla Gutiérrez, Chiapas',
                'image' => 'https://images.unsplash.com/photo-1504198453319-5ce911bafcde',
            ],
            [
                'title' => 'Tour en globo sobre Teotihuacán',
                'desc' => 'Vuela al amanecer sobre las pirámides del Sol y la Luna.',
                'available_date' => '2025-07-01',
                'expiration_date' => '2025-12-31',
                'price' => 2600,
                'rating' => 4.8,
                'status' => true,
                'place' => 'San Juan Teotihuacán, Estado de México',
                'image' => 'https://images.unsplash.com/photo-1529059997568-3f4be1e3edfb',
            ],
            [
                'title' => 'Caminata en el Cañón del Sumidero',
                'desc' => 'Navega o camina por este impresionante cañón natural.',
                'available_date' => '2025-06-01',
                'expiration_date' => '2025-11-30',
                'price' => 800,
                'rating' => 4.5,
                'status' => true,
                'place' => 'Chiapas',
                'image' => 'https://images.unsplash.com/photo-1607042292768-f0a0245fa350',
            ],
            [
                'title' => 'Nado con tortugas en Akumal',
                'desc' => 'Nada con tortugas marinas en su hábitat natural.',
                'available_date' => '2025-05-25',
                'expiration_date' => '2025-10-31',
                'price' => 900,
                'rating' => 4.6,
                'status' => true,
                'place' => 'Akumal, Quintana Roo',
                'image' => 'https://images.unsplash.com/photo-1588947086463-83f0033a97a5',
            ],
            [
                'title' => 'Ruta del Vino en Valle de Guadalupe',
                'desc' => 'Visita viñedos y degusta vinos artesanales mexicanos.',
                'available_date' => '2025-08-01',
                'expiration_date' => '2025-12-31',
                'price' => 1800,
                'rating' => 4.4,
                'status' => true,
                'place' => 'Ensenada, Baja California',
                'image' => 'https://images.unsplash.com/photo-1615309527165-b061f1790cf9',
            ],
            [
                'title' => 'Escalada en la Peña de Bernal',
                'desc' => 'Escala uno de los monolitos más grandes del mundo.',
                'available_date' => '2025-06-01',
                'expiration_date' => '2025-12-31',
                'price' => 700,
                'rating' => 4.2,
                'status' => true,
                'place' => 'Bernal, Querétaro',
                'image' => 'https://images.unsplash.com/photo-1588011757594-b3f0eb46fa5a',
            ],
            [
                'title' => 'Tour gastronómico por Puebla',
                'desc' => 'Degusta mole poblano, chiles en nogada y dulces típicos.',
                'available_date' => '2025-07-10',
                'expiration_date' => '2025-12-10',
                'price' => 950,
                'rating' => 4.7,
                'status' => true,
                'place' => 'Puebla, Puebla',
                'image' => 'https://images.unsplash.com/photo-1612182061245-2a2d72edc27e',
            ],
            [
                'title' => 'Pesca deportiva en Mazatlán',
                'desc' => 'Disfruta un día en altamar buscando marlin y dorado.',
                'available_date' => '2025-07-01',
                'expiration_date' => '2025-12-31',
                'price' => 3000,
                'rating' => 4.3,
                'status' => true,
                'place' => 'Mazatlán, Sinaloa',
                'image' => 'https://images.unsplash.com/photo-1583597928350-f3bc3382640a',
            ],
            [
                'title' => 'Ruta del café en Veracruz',
                'desc' => 'Conoce fincas cafetaleras y degusta café orgánico.',
                'available_date' => '2025-06-01',
                'expiration_date' => '2025-11-30',
                'price' => 850,
                'rating' => 4.5,
                'status' => true,
                'place' => 'Coatepec, Veracruz',
                'image' => 'https://images.unsplash.com/photo-1587733340190-0894df79c3cf',
            ],
            [
                'title' => 'Visita a las Grutas de Tolantongo',
                'desc' => 'Aguas termales en un entorno natural impresionante.',
                'available_date' => '2025-05-30',
                'expiration_date' => '2025-10-30',
                'price' => 700,
                'rating' => 4.6,
                'status' => true,
                'place' => 'Hidalgo',
                'image' => 'https://images.unsplash.com/photo-1581897774154-f2c35e9b51f7',
            ],
            [
                'title' => 'Paseo en trajinera por Xochimilco',
                'desc' => 'Disfruta música, comida y cultura a bordo de una trajinera.',
                'available_date' => '2025-06-01',
                'expiration_date' => '2025-12-01',
                'price' => 600,
                'rating' => 4.1,
                'status' => true,
                'place' => 'CDMX',
                'image' => 'https://images.unsplash.com/photo-1621923839403-728ee1b598ef',
            ],
            [
                'title' => 'Tour arqueológico en Palenque',
                'desc' => 'Explora una de las ciudades mayas más importantes.',
                'available_date' => '2025-07-01',
                'expiration_date' => '2025-12-31',
                'price' => 1100,
                'rating' => 4.8,
                'status' => true,
                'place' => 'Palenque, Chiapas',
                'image' => 'https://images.unsplash.com/photo-1572635196184-dc12b7aeed4d',
            ],
            [
                'title' => 'Paddle board en Bacalar',
                'desc' => 'Navega por la Laguna de los Siete Colores.',
                'available_date' => '2025-06-15',
                'expiration_date' => '2025-11-30',
                'price' => 950,
                'rating' => 4.5,
                'status' => true,
                'place' => 'Bacalar, Quintana Roo',
                'image' => 'https://images.unsplash.com/photo-1592699405463-1959db1fe429',
            ],
            [
                'title' => 'Sandboarding en las dunas de Samalayuca',
                'desc' => 'Deslízate por dunas gigantes en el desierto de Chihuahua.',
                'available_date' => '2025-06-01',
                'expiration_date' => '2025-10-31',
                'price' => 650,
                'rating' => 4.2,
                'status' => true,
                'place' => 'Chihuahua',
                'image' => 'https://images.unsplash.com/photo-1633258022499-bb5f01932c30',
            ],
            [
                'title' => 'Ruta del Queso y Vino en Querétaro',
                'desc' => 'Una experiencia sensorial entre cavas, viñedos y queserías.',
                'available_date' => '2025-08-01',
                'expiration_date' => '2025-12-01',
                'price' => 1300,
                'rating' => 4.6,
                'status' => true,
                'place' => 'Querétaro',
                'image' => 'https://images.unsplash.com/photo-1574878639893-7e58782bc88d',
            ],
            [
                'title' => 'Senderismo en la Huasteca Potosina',
                'desc' => 'Cascadas, pozas turquesa y vegetación exuberante.',
                'available_date' => '2025-06-01',
                'expiration_date' => '2025-11-30',
                'price' => 1500,
                'rating' => 4.9,
                'status' => true,
                'place' => 'San Luis Potosí',
                'image' => 'https://images.unsplash.com/photo-1582313628393-2b7a3a226f69',
            ],
            [
                'title' => 'Nado con tiburón ballena',
                'desc' => 'Aventura marina única en el mundo con el pez más grande del océano.',
                'available_date' => '2025-07-01',
                'expiration_date' => '2025-09-15',
                'price' => 4200,
                'rating' => 5.0,
                'status' => true,
                'place' => 'Isla Holbox, Quintana Roo',
                'image' => 'https://images.unsplash.com/photo-1587547139480-b21581b9be80',
            ],
            [
                'title' => 'Campamento astronómico en Real de Catorce',
                'desc' => 'Observa las estrellas desde uno de los cielos más despejados de México.',
                'available_date' => '2025-09-01',
                'expiration_date' => '2025-12-31',
                'price' => 1000,
                'rating' => 4.3,
                'status' => true,
                'place' => 'San Luis Potosí',
                'image' => 'https://images.unsplash.com/photo-1534707630408-75bcec9b38b7',
            ],
            [
                'title' => 'Ruta de murales en CDMX',
                'desc' => 'Tour guiado por las principales obras de arte urbano.',
                'available_date' => '2025-06-01',
                'expiration_date' => '2025-12-31',
                'price' => 500,
                'rating' => 4.0,
                'status' => true,
                'place' => 'CDMX',
                'image' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71',
            ],
        ];
        foreach ($experiences as $experience) {
            Experience::create($experience);
        }
    }
}
